---
- name: Manage sar package
  ansible.builtin.package:
    name: "{{ sar_package }}"
    state: present

- name: Only for Debian family, update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 172800 # 172880 sec = 2 days
  when: ansible_os_family == 'Debian'

- name: Manage sar logging path
  ansible.builtin.file:
    path: "{{ sar_log_path }}"
    state: directory
    mode: "{{ sar_log_path_mode }}"
    owner: "{{ sar_owner }}"
    group: "{{ sar_group }}"

- name: Manage sar cron content
  ansible.builtin.template:
    src: "templates/sar_cron.j2"
    dest: "{{ sar_cron_file }}"
    owner: "{{ sar_owner }}"
    group: "{{ sar_group }}"
    mode: "{{ sar_cron_file_mode }}"
...
